apiVersion: v1
kind: Pod
metadata:
  name: alpine-image2
  labels:
    app: app1
spec:
  containers:
  - name: alpine-image2
    image: alpine
    #command: ['sh','-c','while true; do sleep infinity; done']
    command: ["sh", "-c", "tail -f /dev/null"]
