---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.122.235:8080"
  restuser: "admin"  
  restuserkey: "My Secret" 
  volumetype: "none"
