apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes Heketi Service
  labels:
    deploy-heketi: service
    glusterfs: heketi-service
  name: deploy-heketi-custom
  namespace: default
spec:
  ports:
  - name: deploy-heketi
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploy-heketi: pod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

