apiVersion: v1
kind: PersistentVolume
metadata:
  name: localvolume
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
  local:
    path: /data/vol01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - centos7-node1.ritay.lan

